/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app.accrescent.tools.bundletool

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'app.accrescent.tools.bundletool.greeting' plugin.
 */
class BundletoolGradlePluginPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("app.accrescent.tools.bundletool.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
